# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    input_sync: true
    default_config: base_config
#    plugins:
#        media:
#            path:     "/vendor/ckeditor/plugin/media/"
#            filename: "plugin.js"

    configs:
        base_config:
            # full, standard, basic, or custom config names
            toolbar: full
            uiColor: #fff1ffd
            filebrowserUploadRoute: upload
            extraAdapters: jquery
            extraPlugins: [ table, image, ajax, codesnippet, codesnippetgeshi, html5video ]

#    toolbars:
#        configs:
#            my_toolbar_1: [ "@document", "/", "@link" , "/", "@tool" ]
#            my_toolbar_2: [ "@document", "/", "@tool"]
#            my_toolbar_3: [ ["Source", "-", "Save"], "/", ["Anchor"], "/", ["Maximize"] ]

        items:
            document: [ "Source", "-", "Save" ]
            link:     [ "Anchor" ]
            tool:     [ "Maximize" ]

    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"