name: Tag Release

on:
  push:
    branches: [ main ]
    tags:
      - "v*"

jobs:
  tag-release:
    name: "Tag Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          files: |
            LICENSE.txt
            *.jar
